version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vpn_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=vpn_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=test1234
      - DATABASE_PORT=5432

volumes:
  postgres_data:
